# See https://github.com/charmbracelet/vhs
# Generate new demo by doing `vhs demo.tape; vhs publish demo.gif`

Output demo.gif

Set Shell "bash"
Set FontSize 24
Set Width 1200
Set Height 800
Set TypingSpeed 50ms

Type "cnpm i && node app.js" Enter Sleep 10s
Type "怎么办理？" Enter Sleep 20s
Type "法律依据？" Enter Sleep 20s
Type "咨询方式？" Enter Sleep 20s
Type "export" Enter Sleep 10s
Type "exit" Enter Sleep 1s
