# See https://github.com/charmbracelet/vhs
# Generate new demo by doing `vhs demo.tape; vhs publish demo.gif`

Output demo.gif

Set Shell "bash"
Set FontSize 24
Set Width 1200
Set Height 800
Set TypingSpeed 50ms

Type "cnpm i && node app.js" Enter Sleep 10s
Type "Hi! 我的名字是 Jason !" Enter Sleep 20s
Type "我的名字是什么?" Enter Sleep 20s
Type "clear" Enter Sleep 10s
Up@5s 2 Enter Sleep 20s
Type "编写Python代码将2个数字相加" Enter Sleep 20s
Type "copy" Enter Sleep 10s
Type "人类是怎样生孩子的？ 仅使用表情符号回复" Enter Sleep 20s
Type "1950 年人口最多的 5 个国家是哪些？表格显示了它们的人口数量？" Enter Sleep 20s
Type "chatgpt plus 会员价格多少?" Enter Sleep 60s
Type "%USERPROFILE%/Downloads/doc.md" Enter Sleep 60s
Type "https://news.sina.cn/2024-03-27/detail-inaptkks3027928.d.html" Enter Sleep 45s
Type "[img] 画一只大猫" Enter Sleep 30s
Type "export" Enter Sleep 10s
Type "exit" Enter Sleep 1s
